online-judge-tools/template-generator

onlinejudge_template/__about__.py
- #11 update the module for the update of Library Checker
- #11 update templates for Windows and macOS
=> RELEASE: 4.1.1

onlinejudge_template/analyzer/parser.py, tests/analyzer_tree.py
fix https://github.com/online-judge-tools/template-generator/issues/13
=> Fix an error of the parser of format strings

onlinejudge_template/generator/python.py, onlinejudge_template_resources/template/main.py
=> Add python.declare_constants() function for the Python generator

onlinejudge_template/__about__.py
-   #14 fix a bug of the parser which is found at [ARC066E](https://atcoder.jp/contests/arc066/tasks/arc066_c)
-   #16 fix a bug of nest arguments in the Python generator
-   #16 add `python.declare_constants()` function for Python templates
=> RELEASE: 4.2.0

onlinejudge_template/__about__.py
- #19 Add the analyzer and the generator for archived problems of Topcoder
- #20 internal refactoring about the analyzer for output patterns
=> RELEASE: 4.3.0

onlinejudge_template/__about__.py
- #25 fix a bug about `long` type in Topcoder
- #25 fix a bug of `main` function in `topcoder.cpp` 
- #26 integrate `topcoder.cpp` into `main.cpp` and remove it
- #26 expose `onlinejudge_template.generator.topcoder` module
=> RELEASE: 4.3.1

onlinejudge_template/analyzer/combined.py, onlinejudge_template/analyzer/match.py, onlinejudge_template/analyzer/output_types.py, onlinejudge_template/analyzer/simple_patterns.py, tests/analyzer_combined.py
ref https://github.com/online-judge-tools/template-generator/issues/8#issuecomment-629743109
=> Update simple_patterns.py to recognize output formats which depend variables in input formats

onlinejudge_template/__about__.py
- https://github.com/online-judge-tools/template-generator/pull/40 colorize logs
=> RELEASE: 4.5.0

onlinejudge_template/__about__.py
- #42 fix some bugs on yukicoder
- #42 fix bugs of MOD detection
=> RELEASE: 4.5.1

README.md, onlinejudge_template/generator/_main.py, onlinejudge_template/generator/hook.py, onlinejudge_template_resources/template/generate.cpp, onlinejudge_template_resources/template/generate.py, onlinejudge_template_resources/template/main.cpp, onlinejudge_template_resources/template/main.py
close #45 
無限に設定項目が増えるタイプの面倒な部分を `clang-format` や `yapf` に丸投げできると、うれしい
=> Use external formatters

onlinejudge_template/__about__.py
- #46 allows to call filter commands (e.g. `clang-format`, `yapf`) as a post-process hook
=> RELEASE: 4.6.0

onlinejudge_template/analyzer/combined.py, onlinejudge_template/analyzer/minimum_tree.py, onlinejudge_template/analyzer/node_util.py, onlinejudge_template/analyzer/parser.py, onlinejudge_template/analyzer/simple_patterns.py, onlinejudge_template/analyzer/simplify.py, onlinejudge_template/analyzer/typing.py, tests/analyzer_minimum_tree.py
=> Improve format guessing from sample cases

onlinejudge_template/__about__.py
- https://github.com/online-judge-tools/template-generator/pull/49 remove `sympy` from the dependency
- https://github.com/online-judge-tools/template-generator/pull/50 improve format guessing from sample cases. Now it can parse  multiple cases formats, which are recently often used on Codeforces.
=> RELEASE: 4.7.0

onlinejudge_template/__about__.py
CHANGELOG:
- #56 fix a syntax error on `generate.py`
=> RELEASE: 4.7.1

tests/analyzer_topcoder.py
そもそも Topcoder 側のエラーで問題文が見えないぽいので
=> Disable one more test for Topcoder

DESIGN.md
related https://github.com/online-judge-tools/.github/pull/4
=> Add DESIGN.md

README.ja.md, README.md
=> Update README for the -webapp

onlinejudge_prepare/main.py, onlinejudge_template/analyzer/combined.py, onlinejudge_template/analyzer/minimum_tree.py, onlinejudge_template/main.py
=> Catch exceptions thoroughly

onlinejudge_template/analyzer/minimum_tree.py
=> Fix a bug of onlinejudge_template/analyzer/minimum_tree.py

onlinejudge_template/__about__.py
=> RELEASE: 4.8.1
